import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Messenger | Sign in',
  description: 'Generated by create next app',
};

export default async function RegisterLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className='w-full h-full bg-sky-200'>{children}</div>;
}
