import { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Messenger | Sign up',
  description: 'Generated by create next app',
};

export default async function RegisterLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  if (session) {
    redirect('/');
  }
  return <div className='w-full h-full bg-sky-200'>{children}</div>;
}
