import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SessionProvider } from '@/context/session';
import { getServerSession } from 'next-auth';
import { Toaster } from 'react-hot-toast';
import NavbarContextProvider from '@/context/navbar-context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Messenger',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang='en'>
      <body className={`${inter.className} bg-gray-100`}>
        <SessionProvider session={session}>
          <NavbarContextProvider>{children}</NavbarContextProvider>
        </SessionProvider>
        <Toaster position='top-center' />
      </body>
    </html>
  );
}
